apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: sa-secret
    shareName: airflow-logs
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
  - mfsymlinks
  